In [1]:
import pandas as pd

# Sample DataFrame with numerical features
data = pd.DataFrame({
    'Feature1': [10, 20, 30, 40, 50],
    'Feature2': [0.1, 0.2, 0.3, 0.4, 0.5],
    'Feature3': [100, 200, 300, 400, 500]
})

print("Original DataFrame:")
print(data)

Original DataFrame:
   Feature1  Feature2  Feature3
0        10       0.1       100
1        20       0.2       200
2        30       0.3       300
3        40       0.4       400
4        50       0.5       500


In [4]:
import numpy as np

data_log_transformed = np.log(data + 1)
data_log_transformed

Feature1  Feature2  Feature3
0  2.397895  0.095310  4.615121
1  3.044522  0.182322  5.303305
2  3.433987  0.262364  5.707110
3  3.713572  0.336472  5.993961
4  3.931826  0.405465  6.216606

In [5]:
from sklearn.preprocessing import PolynomialFeatures

poly = PolynomialFeatures(degree=2, include_bias=False)
data_poly_transformed = poly.fit_transform(data)
data_poly_transformed

array([[1.0e+01, 1.0e-01, 1.0e+02, 1.0e+02, 1.0e+00, 1.0e+03, 1.0e-02,
        1.0e+01, 1.0e+04],
       [2.0e+01, 2.0e-01, 2.0e+02, 4.0e+02, 4.0e+00, 4.0e+03, 4.0e-02,
        4.0e+01, 4.0e+04],
       [3.0e+01, 3.0e-01, 3.0e+02, 9.0e+02, 9.0e+00, 9.0e+03, 9.0e-02,
        9.0e+01, 9.0e+04],
       [4.0e+01, 4.0e-01, 4.0e+02, 1.6e+03, 1.6e+01, 1.6e+04, 1.6e-01,
        1.6e+02, 1.6e+05],
       [5.0e+01, 5.0e-01, 5.0e+02, 2.5e+03, 2.5e+01, 2.5e+04, 2.5e-01,
        2.5e+02, 2.5e+05]])

In [8]:
from scipy.stats import boxcox

# Assuming 'data' is your DataFrame containing numerical features
data_boxcox_transformed = pd.DataFrame()
for column in data.columns:
    data_boxcox_transformed[column], _ = boxcox(data[column].fillna(data[column].mean()))
data_boxcox_transformed

Feature1  Feature2    Feature3
0   5.651388 -1.153078   33.349599
1  10.008081 -0.971708   54.702335
2  13.708443 -0.817662   72.838308
3  17.038106 -0.679048   89.157433
4  20.116742 -0.550884  104.246244

In [9]:
from sklearn.preprocessing import PolynomialFeatures

poly_interaction = PolynomialFeatures(degree=2, interaction_only=True, include_bias=False)
data_interaction_terms = poly_interaction.fit_transform(data)
data_interaction_terms

array([[1.0e+01, 1.0e-01, 1.0e+02, 1.0e+00, 1.0e+03, 1.0e+01],
       [2.0e+01, 2.0e-01, 2.0e+02, 4.0e+00, 4.0e+03, 4.0e+01],
       [3.0e+01, 3.0e-01, 3.0e+02, 9.0e+00, 9.0e+03, 9.0e+01],
       [4.0e+01, 4.0e-01, 4.0e+02, 1.6e+01, 1.6e+04, 1.6e+02],
       [5.0e+01, 5.0e-01, 5.0e+02, 2.5e+01, 2.5e+04, 2.5e+02]])

In [10]:
# # Assuming 'data' is your DataFrame containing numerical features
# data_binned = pd.cut(data, bins=3, labels=["Low", "Medium", "High"], include_lowest=True)
# data_binned

ValueError: Input array must be 1 dimensional

In [11]:
# # Assuming 'data' is your DataFrame containing numerical features
# data_discretized = pd.qcut(data, q=3, labels=["Low", "Medium", "High"])

In [13]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
data_scaled = scaler.fit_transform(data)
data_scaled

array([[0.  , 0.  , 0.  ],
       [0.25, 0.25, 0.25],
       [0.5 , 0.5 , 0.5 ],
       [0.75, 0.75, 0.75],
       [1.  , 1.  , 1.  ]])